// <auto-generated />
namespace CinemAPI.Data.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addingfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201904200715557_Adding field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
